
# for backward compatibility

from shorttext.generators.bow.GensimTopicModeling import gensim_topic_model_dict
from shorttext.generators.bow.LatentTopicModeling import LatentTopicModeler
from shorttext.generators.bow.GensimTopicModeling import GensimTopicModeler
from shorttext.generators.bow.GensimTopicModeling import LDAModeler
from shorttext.generators.bow.GensimTopicModeling import LSIModeler
from shorttext.generators.bow.GensimTopicModeling import RPModeler
from shorttext.generators.bow.AutoEncodingTopicModeling import AutoencodingTopicModeler, load_autoencoder_topicmodel
from shorttext.generators import load_gensimtopicmodel
from shorttext.generators import load_autoencoder_topicmodel as load_autoencoder_topic
