# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_dldist')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_dldist')
    _dldist = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dldist', [dirname(__file__)])
        except ImportError:
            import _dldist
            return _dldist
        try:
            _mod = imp.load_module('_dldist', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _dldist = swig_import_helper()
    del swig_import_helper
else:
    import _dldist
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def damerau_levenshtein(word1, word2):
    """ Return the Damerau-Levenshtein distance between two given words.

    :param word1: a word.
    :param word2: a word.
    :return: Damerau-Levenshtein distance between two words
    :type word1: str
    :type word2: str
    :rtype: int
    """
    return _dldist.damerau_levenshtein(word1, word2)
damerau_levenshtein = _dldist.damerau_levenshtein

def longest_common_prefix(word1, word2):
    """ Return the longest common prefix of the two given words.

    :param word1: a word.
    :param word2: a word.
    :return: the longest common prefix of the two words.
    :type word1: str
    :type word2: str
    :rtype: int
    """
    return _dldist.longest_common_prefix(word1, word2)
longest_common_prefix = _dldist.longest_common_prefix
# This file is compatible with both classic and new-style classes.


